//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int Id { get; set; }
        public string UserFK { get; set; }
        public int ProjectFK { get; set; }
        public decimal Amount { get; set; }
        public string Rewards { get; set; }
        public System.DateTime PaymentDate { get; set; }
        public string PaymentMethod { get; set; }
        public Nullable<decimal> RefundedAmount { get; set; }
        public Nullable<System.DateTime> RefundedDate { get; set; }
        public string TransactionId { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual Project Project { get; set; }
    }
}
