//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Project()
        {
            this.Payment = new HashSet<Payment>();
            this.ProjectFundingLevel = new HashSet<ProjectFundingLevel>();
            this.ProjectPhoto1 = new HashSet<ProjectPhoto>();
        }
    
        public int Id { get; set; }
        public string UserFK { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string ShortDescription { get; set; }
        public decimal Goal { get; set; }
        public Nullable<decimal> GoalMin { get; set; }
        public Nullable<int> MainPhotoFK { get; set; }
        public string Video { get; set; }
        public Nullable<int> CategoryFK { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<System.DateTime> BlockedDate { get; set; }
        public Nullable<int> StateFK { get; set; }
        public string Website { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payment> Payment { get; set; }
        public virtual ProjectCategory ProjectCategory { get; set; }
        public virtual ProjectPhoto ProjectPhoto { get; set; }
        public virtual ProjectState ProjectState { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectFundingLevel> ProjectFundingLevel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectPhoto> ProjectPhoto1 { get; set; }
    }
}
