//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectUpdate
    {
        public int Id { get; set; }
        public int ProjectFK { get; set; }
        public string Message { get; set; }
        public DateTime Date { get; set; }
    
        public virtual Project Project { get; set; }
    }
}
