//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfo
    {
        public int Id { get; set; }
        public string IdentityFK { get; set; }
        public string Mobile { get; set; }
        public string Address { get; set; }
        public System.DateTime BirthDate { get; set; }
        public int Points { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> DeletionDate { get; set; }
        public Nullable<System.DateTime> BlockedDate { get; set; }
        public bool IsAdmin { get; set; }
        public string About { get; set; }
        public string UserName { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<System.DateTime> JoinDate { get; set; }
        public string Phone { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
    }
}
